spring:
  application:
    name: kyc-catalogs
  profiles:
    active: dev
  jackson:
    default-property-inclusion: NON_NULL
    
management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
    session:
      enabled: false

kyc-config:
  catalogs:

    - id: kyc-services
      sql-query: SELECT ID,NAME,COST FROM KYC_SERVICES
      sql-query-id: ID
      command: SQL_QUERY_COMMAND

    - id: kyc-service-status
      sql-query: SELECT ID,DESCRIPTION FROM KYC_SERVICE_STATUS
      sql-query-id: ID
      command: SQL_QUERY_COMMAND

    #- id: kyc-channel
    #  sql-query: SELECT ID,DESCRIPTION FROM KYC_CHANNEL
    #  sql-query-id: ID
    #  command: SQL_QUERY_COMMAND

    - id: kyc-payment-methods
      sql-query: SELECT ID, DESCRIPTION FROM KYC_PAYMENT_METHODS
      sql-query-id: ID
      command: SQL_QUERY_COMMAND

    - id: kyc-states-country
      sql-query: SELECT ID,CODE,DESCRIPTION FROM KYC_STATES_COUNTRY
      sql-query-id: ID
      command: SQL_QUERY_COMMAND

    - id: kyc-transaction-status
      sql-query: SELECT ID, DESCRIPTION FROM KYC_TRANSACTION_STATUS
      sql-id: ID
      command: SQL_QUERY_COMMAND

    - id: kyc-payment-status
      sql-query: SELECT ID, DESCRIPTION FROM KYC_PAYMENT_STATUS
      sql-id: ID
      command: SQL_QUERY_COMMAND

    - id: kyc-user-type
      sql-query: SELECT ID, DESCRIPTION FROM KYC_USER_TYPE
      sql-id: ID
      command: SQL_QUERY_COMMAND

    - id: kyc-batch-id
      sql-query: SELECT ID, DESCRIPTION FROM KYC_BATCH_ID
      sql-query-id: ID
      command: SQL_QUERY_COMMAND

    - id: kyc-batch-error-type
      sql-query: SELECT ID, DESCRIPTION FROM KYC_ERROR_TYPE
      sql-query-id: ID
      command: SQL_QUERY_COMMAND

    - id: kyc-batch-status
      sql-query: SELECT ID, DESCRIPTION FROM KYC_BATCH_STATUS
      sql-query-id: ID
      command: SQL_QUERY_COMMAND

    - id: kyc-report-type
      sql-query: SELECT ID, DESCRIPTION FROM KYC_REPORT_TYPE
      sql-query-id: ID
      command: SQL_QUERY_COMMAND

logging:
  level:
    root: INFO
    com.kyc: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
