spring:
  datasource:
    url: jdbc:postgresql://localhost:6000/kyc_database
    username: kyc_user
    password: kyc_pass
    hikari:
      maximum-pool-size: 1
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

kyc-config:
  cron:
    clean-cache: "0 */5 * * * ?"
  services:
    soap:
      postal-codes:
        url:  http://localhost:9007/kyc/soap/KYCPostalCode
        trace: true

eureka:
  instance:
    preferIpAddress: true
  client:
    enabled: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9100/eureka

logging:
  level:
    root: INFO
    com.kyc: INFO
    org.springframework: INFO
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

server:
  ssl:
    enabled: false
    #client-auth: need
    key-store-type: PKCS12
    key-store: /home/kyc/kyc-config-files/keystore.p12
    key-store-password: test
    key-alias: backbone-key
    #trust-store-type: PKCS12
    #trust-store: /home/kyc/kyc-config-files/keystore.p12
    #trust-store-password: test