spring:
  application:
    name: kyc-catalogs
  profiles:
    active: dev
  jackson:
    default-property-inclusion: NON_NULL

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
    external-services:
      enabled: true
  info:
    build:
      enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    enabled: false

kyc-config:
  catalogs:

    - id: kyc-services
      type: both
      sql-queries:
        all-query: SELECT ID,NAME,COST FROM KYC_SERVICES
        single-query: SELECT ID,NAME,COST FROM KYC_SERVICES WHERE ID = ?
      command: SQL_QUERY_COMMAND

    - id: kyc-service-status
      type: both
      sql-queries:
        all-query: SELECT ID,DESCRIPTION FROM KYC_SERVICE_STATUS
        single-query: SELECT ID,DESCRIPTION FROM KYC_SERVICE_STATUS WHERE ID = ?
      command: SQL_QUERY_COMMAND

    - id: kyc-channel
      type: both
      sql-queries:
        all-query: SELECT ID,DESCRIPTION FROM KYC_CHANNEL
        single-query: SELECT ID,DESCRIPTION FROM KYC_CHANNEL WHERE ID = ?
      command: SQL_QUERY_COMMAND

    - id: kyc-payment-methods
      type: both
      sql-queries:
        all-query: SELECT ID, DESCRIPTION FROM KYC_PAYMENT_METHODS
        single-query: SELECT ID,DESCRIPTION FROM KYC_PAYMENT_METHODS WHERE ID = ?
      command: SQL_QUERY_COMMAND

    - id: kyc-states-country
      type: both
      sql-queries:
        all-query: SELECT ID,CODE,DESCRIPTION FROM KYC_STATES_COUNTRY
        single-query: SELECT ID,CODE,DESCRIPTION FROM KYC_STATES_COUNTRY WHERE ID = ?
      command: SQL_QUERY_COMMAND

    - id: kyc-transaction-status
      type: both
      sql-queries:
        all-query: SELECT ID, DESCRIPTION FROM KYC_TRANSACTION_STATUS
        single-query: SELECT ID, DESCRIPTION FROM KYC_TRANSACTION_STATUS WHERE ID = ?
      command: SQL_QUERY_COMMAND

    - id: kyc-payment-status
      type: both
      sql-queries:
        all-query: SELECT ID, DESCRIPTION FROM KYC_PAYMENT_STATUS
        single-query: SELECT ID, DESCRIPTION FROM KYC_PAYMENT_STATUS WHERE ID = ?
      command: SQL_QUERY_COMMAND

    - id: kyc-user-type
      type: both
      sql-queries:
        all-query: SELECT ID, DESCRIPTION FROM KYC_USER_TYPE
        single-query: SELECT ID, DESCRIPTION FROM KYC_USER_TYPE WHERE ID = ?
      command: SQL_QUERY_COMMAND

    - id: kyc-batch-id
      type: both
      sql-queries:
        all-query: SELECT ID, DESCRIPTION FROM KYC_BATCH_ID
        single-query: SELECT ID, DESCRIPTION FROM KYC_BATCH_ID WHERE ID = ?
      command: SQL_QUERY_COMMAND

    - id: kyc-report-type
      type: both
      sql-queries:
        all-query: SELECT ID, DESCRIPTION FROM KYC_REPORT_TYPE
        single-query: SELECT ID, DESCRIPTION FROM KYC_REPORT_TYPE WHERE ID = ?
      command: SQL_QUERY_COMMAND

    - id: kyc-offices
      type: both
      sql-queries:
        all-query: SELECT * FROM SP_KYC_GET_OFFICE(?,?,?,?,?)
        id: SELECT * FROM SP_KYC_GET_OFFICE(?,'','','',TRUE)
      command: QUERY_OFFICES_COMMAND

    - id: kyc-postal-codes
      type: single
      command: POSTAL_CODE_WS_COMMAND

kyc-messages:
  catalog:
    messages:
      "001":
        code: KYC-CATALOGS-001
        message: Unexpected Error
        type: ERROR
      "002":
        code: KYC-CATALOGS-002
        message: The element was not found
        type: WARN
      "003":
        code: KYC-CATALOGS-003
        message: The catalog was not found
        type: WARN