DROP TABLE IF EXISTS SERVICES;
DROP TABLE IF EXISTS SERVICE_STATUS;
DROP TABLE IF EXISTS AUTHORIZED_BANKS;
DROP TABLE IF EXISTS PAYMENT_METHODS;
DROP TABLE IF EXISTS STATES_COUNTRY;

CREATE TABLE SERVICES(
    ID SERIAL,
    NAME VARCHAR(50) NOT NULL,
    COST VARCHAR(10) NOT NULL
);

CREATE TABLE SERVICE_STATUS(
    ID SERIAL,
    DESCRIPTION VARCHAR(20) NOT NULL
);

CREATE TABLE AUTHORIZED_BANKS(
    ID SERIAL,
    CVE_BANK VARCHAR(3),
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE PAYMENT_METHODS(
    ID SERIAL,
    METHOD VARCHAR(50) NOT NULL
);

CREATE TABLE STATES_COUNTRY(
    ID SERIAL,
    CODE VARCHAR(3),
    DESCRIPTION VARCHAR(50)
);

ALTER TABLE SERVICES ADD PRIMARY KEY(ID);
ALTER TABLE AUTHORIZED_BANKS ADD PRIMARY KEY(ID);
ALTER TABLE PAYMENT_METHODS ADD PRIMARY KEY(ID);
ALTER TABLE SERVICE_STATUS ADD PRIMARY KEY(ID);
ALTER TABLE STATES_COUNTRY ADD PRIMARY KEY(ID);

INSERT INTO SERVICES(NAME,COST) VALUES('Solo Internet','15');
INSERT INTO SERVICES(NAME,COST) VALUES('Internet y Netflix','25');
INSERT INTO SERVICES(NAME,COST) VALUES('Solo TV Cable','14');
INSERT INTO SERVICES(NAME,COST) VALUES('Internet y TV Cable','28');
INSERT INTO SERVICES(NAME,COST) VALUES('Internet, TV Cable y Netflix','30');

INSERT INTO SERVICE_STATUS(DESCRIPTION) VALUES('Activo');
INSERT INTO SERVICE_STATUS(DESCRIPTION) VALUES('Suspendido');
INSERT INTO SERVICE_STATUS(DESCRIPTION) VALUES('Cancelado');

INSERT INTO AUTHORIZED_BANKS(CVE_BANK,NAME) VALUES('SB','Banco Sarang');
INSERT INTO AUTHORIZED_BANKS(CVE_BANK,NAME) VALUES('SK','Banco Kenkou');
INSERT INTO AUTHORIZED_BANKS(CVE_BANK,NAME) VALUES('SR','Banco La Raza');

INSERT INTO PAYMENT_METHODS(METHOD) VALUES('Ventanilla Bancaria');
INSERT INTO PAYMENT_METHODS(METHOD) VALUES('Paypal');
INSERT INTO PAYMENT_METHODS(METHOD) VALUES('Tarjeta de Credito');
INSERT INTO PAYMENT_METHODS(METHOD) VALUES('Tiendas de autoservicio');

INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Aguascalientes','AS');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Baja California','BC');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Baja California Sur','BS');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Campeche','CC');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Chiapas','CS');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Chihuahua','CH');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Ciudad de Mexico','DF');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Coahuila','CL');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Colima','CM');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Durango','DG');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Guanajuato','GT');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Guerrero','GR');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Hidalgo','HG');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Jalisco','JC');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Estado de Mexico','MC');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Michoacan','MN');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Morelos','MS');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Nayarit','NT');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Nuevo Leon','NL');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Oaxaca','OC');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Puebla','PL');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Queretaro','QO');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Quintana Roo','QR');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('San Luis Potosi','SP');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Sinaloa','SL');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Sonora','SR');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Tabasco','TC');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Tamaulipas','TS');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Tlaxcala','TL');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Veracruz','VZ');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Yucatan','YN');
INSERT INTO STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Zacatecas','ZS');